"""
app/routes/scans.py
POST /scans/predict   — upload X-ray + intake info, run model, save scan record
GET  /scans/{id}       — get full scan details (for viewing/report)
PUT  /scans/{id}/review — doctor saves notes / override
"""

import os
import uuid
from datetime import datetime, date
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import Optional

from app.database import get_db
from app.models_db import Scan, Patient, User
from app.routes.auth import get_current_user
from app.model_loader import preprocess, predict_ensemble, ModelHolder, TARGET_CONDITIONS, val_transforms
from utils.gradcam import generate_gradcam_b64, GradCAM

router = APIRouter()

STORAGE_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "storage")
XRAY_DIR = os.path.join(STORAGE_DIR, "xrays")
GRADCAM_DIR = os.path.join(STORAGE_DIR, "gradcams")
os.makedirs(XRAY_DIR, exist_ok=True)
os.makedirs(GRADCAM_DIR, exist_ok=True)


# ── Schemas ───────────────────────────────────────────────────────
class ScanResponse(BaseModel):
    id: int
    patient_id: int
    patient_name: str
    department: str
    scan_date: str
    triage: Optional[str]
    top_condition: Optional[str]
    confidence: Optional[float]
    findings: dict
    gradcam_base64: Optional[str] = None
    doctor_notes: Optional[str] = None
    override: Optional[str] = None
    disclaimer: str = (
        "This result is generated by an AI screening tool and must be reviewed "
        "by a licensed radiologist or physician before any clinical decision is made. "
        "This system is not FDA-approved."
    )


class ReviewRequest(BaseModel):
    doctor_notes: Optional[str] = None
    override: Optional[str] = None   # "confirm" | "normal" | "abnormal" | "refer"


# ── Routes ────────────────────────────────────────────────────────
@router.post("/predict", response_model=ScanResponse)
async def predict_and_save(
    patient_id: int = Form(...),
    department: str = Form(...),
    scan_date: str = Form(...),       # ISO format YYYY-MM-DD
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    # ── Validate patient ──
    patient = db.query(Patient).filter(Patient.id == patient_id).first()
    if not patient:
        raise HTTPException(status_code=404, detail="Patient not found.")

    # ── Validate file ──
    if file.content_type not in ["image/png", "image/jpeg", "image/jpg"]:
        raise HTTPException(status_code=415, detail="Upload PNG or JPEG only.")

    image_bytes = await file.read()
    if len(image_bytes) > 10 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="File too large. Maximum 10 MB.")

    # ── Save original image ──
    file_id = str(uuid.uuid4())[:12]
    ext = ".png" if file.content_type == "image/png" else ".jpg"
    image_filename = f"{file_id}{ext}"
    image_path = os.path.join(XRAY_DIR, image_filename)
    with open(image_path, "wb") as f:
        f.write(image_bytes)

    # ── Run ensemble prediction ──
    tensor = preprocess(image_bytes)
    result = predict_ensemble(tensor)

    # ── Grad-CAM ──
    gradcam_filename = None
    gradcam_b64 = None
    if not ModelHolder.mock and ModelHolder.b0 is not None:
        top_idx = TARGET_CONDITIONS.index(result["top_condition"])
        try:
            gradcam_b64 = generate_gradcam_b64(
                model=ModelHolder.b0,
                image_bytes=image_bytes,
                class_idx=top_idx,
                val_transforms=val_transforms,
            )
            # save gradcam to disk too, for report generation later
            import base64
            gradcam_filename = f"{file_id}_gradcam.png"
            gradcam_path = os.path.join(GRADCAM_DIR, gradcam_filename)
            with open(gradcam_path, "wb") as f:
                f.write(base64.b64decode(gradcam_b64))
        except Exception as e:
            print(f"Grad-CAM generation failed: {e}")

    # ── Parse scan_date ──
    try:
        parsed_scan_date = datetime.strptime(scan_date, "%Y-%m-%d").date()
    except ValueError:
        parsed_scan_date = date.today()

    # ── Save scan record ──
    findings = result["findings"]
    scan = Scan(
        patient_id=patient.id,
        doctor_id=current_user.id,
        department=department,
        scan_date=parsed_scan_date,
        image_path=image_path,
        gradcam_path=os.path.join(GRADCAM_DIR, gradcam_filename) if gradcam_filename else None,
        triage=result["triage"],
        top_condition=result["top_condition"],
        confidence=result["confidence"],
        no_finding_prob=findings.get("No Finding"),
        pneumonia_prob=findings.get("Pneumonia"),
        cardiomegaly_prob=findings.get("Cardiomegaly"),
        effusion_prob=findings.get("Effusion"),
        infiltration_prob=findings.get("Infiltration"),
    )
    db.add(scan)
    db.commit()
    db.refresh(scan)

    return ScanResponse(
        id=scan.id,
        patient_id=patient.id,
        patient_name=patient.name,
        department=department,
        scan_date=scan_date,
        triage=scan.triage,
        top_condition=scan.top_condition,
        confidence=scan.confidence,
        findings=findings,
        gradcam_base64=gradcam_b64,
        doctor_notes=scan.doctor_notes,
        override=scan.override,
    )


@router.get("/{scan_id}", response_model=ScanResponse)
def get_scan(
    scan_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found.")

    findings = {
        "No Finding": scan.no_finding_prob,
        "Pneumonia": scan.pneumonia_prob,
        "Cardiomegaly": scan.cardiomegaly_prob,
        "Effusion": scan.effusion_prob,
        "Infiltration": scan.infiltration_prob,
    }

    gradcam_b64 = None
    if scan.gradcam_path and os.path.exists(scan.gradcam_path):
        import base64
        with open(scan.gradcam_path, "rb") as f:
            gradcam_b64 = base64.b64encode(f.read()).decode("utf-8")

    return ScanResponse(
        id=scan.id,
        patient_id=scan.patient_id,
        patient_name=scan.patient.name,
        department=scan.department,
        scan_date=scan.scan_date.isoformat(),
        triage=scan.triage,
        top_condition=scan.top_condition,
        confidence=scan.confidence,
        findings=findings,
        gradcam_base64=gradcam_b64,
        doctor_notes=scan.doctor_notes,
        override=scan.override,
    )


@router.put("/{scan_id}/review")
def review_scan(
    scan_id: int,
    body: ReviewRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found.")

    scan.doctor_notes = body.doctor_notes
    scan.override = body.override
    scan.reviewed_at = datetime.utcnow()
    db.commit()

    return {"message": "Review saved.", "scan_id": scan.id}
