apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medsight-data
  namespace: medsight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medsight-models
  namespace: medsight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi